version: '3.4'

services:
  frontend:
    restart: always
    image: $DOCKER_FRONTEND_IMAGE
    networks:
      default:
        aliases:
        - frontend

  backend:
    restart: always
    image: $DOCKER_BACKEND_IMAGE
    env_file: .env
    volumes:
    - media_data:/var/www/run/media
    depends_on:
    - postgres
    networks:
       default:
         aliases:
         - backend

  api:
    restart: always
    image: $DOCKER_API_IMAGE
    env_file: .env
    depends_on:
    - postgres
    volumes:
    - ./static:/root/static
    networks:
       default:
         aliases:
         - api

  nginx:
    restart: always
    image: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - /etc/nginx:/etc/nginx
    - ./static:/var/www/static

  postgres:
    restart: always
    container_name: postgres
    image: postgres:11
    ports:
    - 0.0.0.0:5432:5432
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  caddy_data:
  media_data:
  pg_data: